spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://accounts.flowalp.com/realms/flowalp"
  datasource:
    url: "jdbc:mysql://localhost:3306/event_flowalp?useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "Admin123"
  jpa:
    hibernate:
      ddl-auto: update

api:
  url: /api/v1

cors:
  allowed-origins: "http://localhost:4200"

server:
  port: 3000