spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: event
  datasource:
    url: jdbc:mysql://localhost:3306/event_flowalp?useSSL=false&
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # "update" for dev, "validate" for prod


---
spring:
  config:
    activate:
      on-profile: prod