spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: event
    version: 0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/event_flowalp?useSSL=false&allowPublicKeyRetrieval=true
    username: nuovo_utente
    password: tua_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # "update" for dev, "validate" for prod
server:
  port: 3000
---
spring:
  config:
    activate:
      on-profile: prod